# Generated by Django 2.2.16 on 2022-08-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='posts.Group'),
        ),
    ]
